//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.EntityClient;
using ReBus.Model;

namespace ReBus.Repository
{
    public partial class ReBusContainer : ObjectContext
    {
        public const string ConnectionString = "name=ReBusContainer";
        public const string ContainerName = "ReBusContainer";
    
        #region Constructors
    
        public ReBusContainer()
            : base(ConnectionString, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
        }
    
        public ReBusContainer(string connectionString)
            : base(connectionString, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
        }
    
        public ReBusContainer(EntityConnection connection)
            : base(connection, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
        }
    
        #endregion
    
        #region ObjectSet Properties
    
        public ObjectSet<Account> Accounts
        {
            get { return _accounts  ?? (_accounts = CreateObjectSet<Account>("Accounts")); }
        }
        private ObjectSet<Account> _accounts;
    
        public ObjectSet<Transaction> Transactions
        {
            get { return _transactions  ?? (_transactions = CreateObjectSet<Transaction>("Transactions")); }
        }
        private ObjectSet<Transaction> _transactions;
    
        public ObjectSet<Line> Lines
        {
            get { return _lines  ?? (_lines = CreateObjectSet<Line>("Lines")); }
        }
        private ObjectSet<Line> _lines;
    
        public ObjectSet<Bus> Buses
        {
            get { return _buses  ?? (_buses = CreateObjectSet<Bus>("Buses")); }
        }
        private ObjectSet<Bus> _buses;
    
        public ObjectSet<Ticket> Tickets
        {
            get { return _tickets  ?? (_tickets = CreateObjectSet<Ticket>("Tickets")); }
        }
        private ObjectSet<Ticket> _tickets;
    
        public ObjectSet<Subscription> Subscriptions
        {
            get { return _subscriptions  ?? (_subscriptions = CreateObjectSet<Subscription>("Subscriptions")); }
        }
        private ObjectSet<Subscription> _subscriptions;
    
        public ObjectSet<TicketCost> TicketCost
        {
            get { return _ticketCost  ?? (_ticketCost = CreateObjectSet<TicketCost>("TicketCost")); }
        }
        private ObjectSet<TicketCost> _ticketCost;
    
        public ObjectSet<SubscriptionCost> SubscriptionCosts
        {
            get { return _subscriptionCosts  ?? (_subscriptionCosts = CreateObjectSet<SubscriptionCost>("SubscriptionCosts")); }
        }
        private ObjectSet<SubscriptionCost> _subscriptionCosts;
    
        public ObjectSet<Station> Stations
        {
            get { return _stations  ?? (_stations = CreateObjectSet<Station>("Stations")); }
        }
        private ObjectSet<Station> _stations;

        #endregion
    }
}
