//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.EntityClient;
using ReBus.Model;

namespace ReBus.Repository
{
    public partial class Model1Container : ObjectContext
    {
        public const string ConnectionString = "name=Model1Container";
        public const string ContainerName = "Model1Container";
    
        #region Constructors
    
        public Model1Container()
            : base(ConnectionString, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
        }
    
        public Model1Container(string connectionString)
            : base(connectionString, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
        }
    
        public Model1Container(EntityConnection connection)
            : base(connection, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
        }
    
        #endregion
    
        #region ObjectSet Properties
    
        public ObjectSet<Account> Accounts
        {
            get { return _accounts  ?? (_accounts = CreateObjectSet<Account>("Accounts")); }
        }
        private ObjectSet<Account> _accounts;
    
        public ObjectSet<Transaction> Transactions
        {
            get { return _transactions  ?? (_transactions = CreateObjectSet<Transaction>("Transactions")); }
        }
        private ObjectSet<Transaction> _transactions;
    
        public ObjectSet<Line> Lines
        {
            get { return _lines  ?? (_lines = CreateObjectSet<Line>("Lines")); }
        }
        private ObjectSet<Line> _lines;
    
        public ObjectSet<Bus> Buses
        {
            get { return _buses  ?? (_buses = CreateObjectSet<Bus>("Buses")); }
        }
        private ObjectSet<Bus> _buses;
    
        public ObjectSet<Ticket> Tickets
        {
            get { return _tickets  ?? (_tickets = CreateObjectSet<Ticket>("Tickets")); }
        }
        private ObjectSet<Ticket> _tickets;
    
        public ObjectSet<Subscription> Subscriptions
        {
            get { return _subscriptions  ?? (_subscriptions = CreateObjectSet<Subscription>("Subscriptions")); }
        }
        private ObjectSet<Subscription> _subscriptions;

        #endregion
    }
}
