//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace ReBus.Model
{
    public partial class Subscription
    {
        #region Primitive Properties
    
        public virtual System.Guid GUID
        {
            get;
            set;
        }
    
        public virtual System.Guid AccountGUID
        {
            get { return _accountGUID; }
            set
            {
                if (_accountGUID != value)
                {
                    if (Account != null && Account.GUID != value)
                    {
                        Account = null;
                    }
                    _accountGUID = value;
                }
            }
        }
        private System.Guid _accountGUID;
    
        public virtual System.DateTime Start
        {
            get;
            set;
        }
    
        public virtual System.DateTime End
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual Account Account
        {
            get { return _account; }
            set
            {
                if (!ReferenceEquals(_account, value))
                {
                    var previousValue = _account;
                    _account = value;
                    FixupAccount(previousValue);
                }
            }
        }
        private Account _account;
    
        public virtual ICollection<Line> Lines
        {
            get
            {
                if (_lines == null)
                {
                    var newCollection = new FixupCollection<Line>();
                    newCollection.CollectionChanged += FixupLines;
                    _lines = newCollection;
                }
                return _lines;
            }
            set
            {
                if (!ReferenceEquals(_lines, value))
                {
                    var previousValue = _lines as FixupCollection<Line>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupLines;
                    }
                    _lines = value;
                    var newValue = value as FixupCollection<Line>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupLines;
                    }
                }
            }
        }
        private ICollection<Line> _lines;

        #endregion
        #region Association Fixup
    
        private void FixupAccount(Account previousValue)
        {
            if (previousValue != null && previousValue.Subscriptions.Contains(this))
            {
                previousValue.Subscriptions.Remove(this);
            }
    
            if (Account != null)
            {
                if (!Account.Subscriptions.Contains(this))
                {
                    Account.Subscriptions.Add(this);
                }
                if (AccountGUID != Account.GUID)
                {
                    AccountGUID = Account.GUID;
                }
            }
        }
    
        private void FixupLines(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (Line item in e.NewItems)
                {
                    if (!item.Subscriptions.Contains(this))
                    {
                        item.Subscriptions.Add(this);
                    }
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (Line item in e.OldItems)
                {
                    if (item.Subscriptions.Contains(this))
                    {
                        item.Subscriptions.Remove(this);
                    }
                }
            }
        }

        #endregion
    }
}
