//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace ReBus.Model
{
    public partial class Ticket
    {
        #region Primitive Properties
    
        public virtual System.Guid GUID
        {
            get;
            set;
        }
    
        public virtual System.Guid AccountGUID
        {
            get { return _accountGUID; }
            set
            {
                if (_accountGUID != value)
                {
                    if (Account != null && Account.GUID != value)
                    {
                        Account = null;
                    }
                    _accountGUID = value;
                }
            }
        }
        private System.Guid _accountGUID;
    
        public virtual System.DateTime Created
        {
            get;
            set;
        }
    
        public virtual System.Guid BusGUID
        {
            get { return _busGUID; }
            set
            {
                if (_busGUID != value)
                {
                    if (Bus != null && Bus.GUID != value)
                    {
                        Bus = null;
                    }
                    _busGUID = value;
                }
            }
        }
        private System.Guid _busGUID;

        #endregion
        #region Navigation Properties
    
        public virtual Account Account
        {
            get { return _account; }
            set
            {
                if (!ReferenceEquals(_account, value))
                {
                    var previousValue = _account;
                    _account = value;
                    FixupAccount(previousValue);
                }
            }
        }
        private Account _account;
    
        public virtual Bus Bus
        {
            get { return _bus; }
            set
            {
                if (!ReferenceEquals(_bus, value))
                {
                    var previousValue = _bus;
                    _bus = value;
                    FixupBus(previousValue);
                }
            }
        }
        private Bus _bus;

        #endregion
        #region Association Fixup
    
        private void FixupAccount(Account previousValue)
        {
            if (previousValue != null && previousValue.Tickets.Contains(this))
            {
                previousValue.Tickets.Remove(this);
            }
    
            if (Account != null)
            {
                if (!Account.Tickets.Contains(this))
                {
                    Account.Tickets.Add(this);
                }
                if (AccountGUID != Account.GUID)
                {
                    AccountGUID = Account.GUID;
                }
            }
        }
    
        private void FixupBus(Bus previousValue)
        {
            if (previousValue != null && previousValue.Tickets.Contains(this))
            {
                previousValue.Tickets.Remove(this);
            }
    
            if (Bus != null)
            {
                if (!Bus.Tickets.Contains(this))
                {
                    Bus.Tickets.Add(this);
                }
                if (BusGUID != Bus.GUID)
                {
                    BusGUID = Bus.GUID;
                }
            }
        }

        #endregion
    }
}
