//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.Phone.ServiceReference, version 3.7.0.0
// 
namespace ReBus.Mobile.InformationServiceReference {
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GeneralInformationWebServiceModel", Namespace="http://schemas.datacontract.org/2004/07/ReBus.WebServices.WebServiceModel")]
    public partial class GeneralInformationWebServiceModel : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Collections.ObjectModel.ObservableCollection<ReBus.Mobile.InformationServiceReference.LineWebServiceModel> LinesField;
        
        private System.Collections.Generic.Dictionary<int, decimal> SubscriptionPricesField;
        
        private decimal TicketPriceField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.ObjectModel.ObservableCollection<ReBus.Mobile.InformationServiceReference.LineWebServiceModel> Lines {
            get {
                return this.LinesField;
            }
            set {
                if ((object.ReferenceEquals(this.LinesField, value) != true)) {
                    this.LinesField = value;
                    this.RaisePropertyChanged("Lines");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<int, decimal> SubscriptionPrices {
            get {
                return this.SubscriptionPricesField;
            }
            set {
                if ((object.ReferenceEquals(this.SubscriptionPricesField, value) != true)) {
                    this.SubscriptionPricesField = value;
                    this.RaisePropertyChanged("SubscriptionPrices");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal TicketPrice {
            get {
                return this.TicketPriceField;
            }
            set {
                if ((this.TicketPriceField.Equals(value) != true)) {
                    this.TicketPriceField = value;
                    this.RaisePropertyChanged("TicketPrice");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LineWebServiceModel", Namespace="http://schemas.datacontract.org/2004/07/ReBus.WebServices.WebServiceModel")]
    public partial class LineWebServiceModel : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Guid GUIDField;
        
        private string NameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid GUID {
            get {
                return this.GUIDField;
            }
            set {
                if ((this.GUIDField.Equals(value) != true)) {
                    this.GUIDField = value;
                    this.RaisePropertyChanged("GUID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TicketWebServiceModel", Namespace="http://schemas.datacontract.org/2004/07/ReBus.WebServices.WebServiceModel")]
    public partial class TicketWebServiceModel : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ReBus.Mobile.InformationServiceReference.AccountWebServiceModel AccountField;
        
        private ReBus.Mobile.InformationServiceReference.BusWebServiceModel BusField;
        
        private System.DateTime CreatedField;
        
        private System.Guid GUIDField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ReBus.Mobile.InformationServiceReference.AccountWebServiceModel Account {
            get {
                return this.AccountField;
            }
            set {
                if ((object.ReferenceEquals(this.AccountField, value) != true)) {
                    this.AccountField = value;
                    this.RaisePropertyChanged("Account");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ReBus.Mobile.InformationServiceReference.BusWebServiceModel Bus {
            get {
                return this.BusField;
            }
            set {
                if ((object.ReferenceEquals(this.BusField, value) != true)) {
                    this.BusField = value;
                    this.RaisePropertyChanged("Bus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Created {
            get {
                return this.CreatedField;
            }
            set {
                if ((this.CreatedField.Equals(value) != true)) {
                    this.CreatedField = value;
                    this.RaisePropertyChanged("Created");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid GUID {
            get {
                return this.GUIDField;
            }
            set {
                if ((this.GUIDField.Equals(value) != true)) {
                    this.GUIDField = value;
                    this.RaisePropertyChanged("GUID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AccountWebServiceModel", Namespace="http://schemas.datacontract.org/2004/07/ReBus.WebServices.WebServiceModel")]
    public partial class AccountWebServiceModel : object, System.ComponentModel.INotifyPropertyChanged {
        
        private decimal CreditField;
        
        private string FirstNameField;
        
        private System.Guid GUIDField;
        
        private string LastNameField;
        
        private string UserNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Credit {
            get {
                return this.CreditField;
            }
            set {
                if ((this.CreditField.Equals(value) != true)) {
                    this.CreditField = value;
                    this.RaisePropertyChanged("Credit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid GUID {
            get {
                return this.GUIDField;
            }
            set {
                if ((this.GUIDField.Equals(value) != true)) {
                    this.GUIDField = value;
                    this.RaisePropertyChanged("GUID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BusWebServiceModel", Namespace="http://schemas.datacontract.org/2004/07/ReBus.WebServices.WebServiceModel")]
    public partial class BusWebServiceModel : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Guid GUIDField;
        
        private ReBus.Mobile.InformationServiceReference.LineWebServiceModel LineField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid GUID {
            get {
                return this.GUIDField;
            }
            set {
                if ((this.GUIDField.Equals(value) != true)) {
                    this.GUIDField = value;
                    this.RaisePropertyChanged("GUID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ReBus.Mobile.InformationServiceReference.LineWebServiceModel Line {
            get {
                return this.LineField;
            }
            set {
                if ((object.ReferenceEquals(this.LineField, value) != true)) {
                    this.LineField = value;
                    this.RaisePropertyChanged("Line");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SubscriptionWebServiceModel", Namespace="http://schemas.datacontract.org/2004/07/ReBus.WebServices.WebServiceModel")]
    public partial class SubscriptionWebServiceModel : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ReBus.Mobile.InformationServiceReference.AccountWebServiceModel AccountField;
        
        private System.DateTime CreatedField;
        
        private System.DateTime EndField;
        
        private System.Guid GUIDField;
        
        private System.Collections.ObjectModel.ObservableCollection<ReBus.Mobile.InformationServiceReference.LineWebServiceModel> LinesField;
        
        private System.DateTime StartField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ReBus.Mobile.InformationServiceReference.AccountWebServiceModel Account {
            get {
                return this.AccountField;
            }
            set {
                if ((object.ReferenceEquals(this.AccountField, value) != true)) {
                    this.AccountField = value;
                    this.RaisePropertyChanged("Account");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Created {
            get {
                return this.CreatedField;
            }
            set {
                if ((this.CreatedField.Equals(value) != true)) {
                    this.CreatedField = value;
                    this.RaisePropertyChanged("Created");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime End {
            get {
                return this.EndField;
            }
            set {
                if ((this.EndField.Equals(value) != true)) {
                    this.EndField = value;
                    this.RaisePropertyChanged("End");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid GUID {
            get {
                return this.GUIDField;
            }
            set {
                if ((this.GUIDField.Equals(value) != true)) {
                    this.GUIDField = value;
                    this.RaisePropertyChanged("GUID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.ObjectModel.ObservableCollection<ReBus.Mobile.InformationServiceReference.LineWebServiceModel> Lines {
            get {
                return this.LinesField;
            }
            set {
                if ((object.ReferenceEquals(this.LinesField, value) != true)) {
                    this.LinesField = value;
                    this.RaisePropertyChanged("Lines");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Start {
            get {
                return this.StartField;
            }
            set {
                if ((this.StartField.Equals(value) != true)) {
                    this.StartField = value;
                    this.RaisePropertyChanged("Start");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="InformationServiceReference.IInformationWebService")]
    public interface IInformationWebService {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IInformationWebService/GetGeneralInformation", ReplyAction="http://tempuri.org/IInformationWebService/GetGeneralInformationResponse")]
        System.IAsyncResult BeginGetGeneralInformation(System.AsyncCallback callback, object asyncState);
        
        ReBus.Mobile.InformationServiceReference.GeneralInformationWebServiceModel EndGetGeneralInformation(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IInformationWebService/GetTicket", ReplyAction="http://tempuri.org/IInformationWebService/GetTicketResponse")]
        System.IAsyncResult BeginGetTicket(System.Guid guid, System.AsyncCallback callback, object asyncState);
        
        ReBus.Mobile.InformationServiceReference.TicketWebServiceModel EndGetTicket(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IInformationWebService/GetSubscription", ReplyAction="http://tempuri.org/IInformationWebService/GetSubscriptionResponse")]
        System.IAsyncResult BeginGetSubscription(System.Guid guid, System.AsyncCallback callback, object asyncState);
        
        ReBus.Mobile.InformationServiceReference.SubscriptionWebServiceModel EndGetSubscription(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IInformationWebService/GetBus", ReplyAction="http://tempuri.org/IInformationWebService/GetBusResponse")]
        System.IAsyncResult BeginGetBus(System.Guid guid, System.AsyncCallback callback, object asyncState);
        
        ReBus.Mobile.InformationServiceReference.BusWebServiceModel EndGetBus(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IInformationWebServiceChannel : ReBus.Mobile.InformationServiceReference.IInformationWebService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetGeneralInformationCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetGeneralInformationCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public ReBus.Mobile.InformationServiceReference.GeneralInformationWebServiceModel Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((ReBus.Mobile.InformationServiceReference.GeneralInformationWebServiceModel)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetTicketCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetTicketCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public ReBus.Mobile.InformationServiceReference.TicketWebServiceModel Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((ReBus.Mobile.InformationServiceReference.TicketWebServiceModel)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetSubscriptionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetSubscriptionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public ReBus.Mobile.InformationServiceReference.SubscriptionWebServiceModel Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((ReBus.Mobile.InformationServiceReference.SubscriptionWebServiceModel)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetBusCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetBusCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public ReBus.Mobile.InformationServiceReference.BusWebServiceModel Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((ReBus.Mobile.InformationServiceReference.BusWebServiceModel)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class InformationWebServiceClient : System.ServiceModel.ClientBase<ReBus.Mobile.InformationServiceReference.IInformationWebService>, ReBus.Mobile.InformationServiceReference.IInformationWebService {
        
        private BeginOperationDelegate onBeginGetGeneralInformationDelegate;
        
        private EndOperationDelegate onEndGetGeneralInformationDelegate;
        
        private System.Threading.SendOrPostCallback onGetGeneralInformationCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetTicketDelegate;
        
        private EndOperationDelegate onEndGetTicketDelegate;
        
        private System.Threading.SendOrPostCallback onGetTicketCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetSubscriptionDelegate;
        
        private EndOperationDelegate onEndGetSubscriptionDelegate;
        
        private System.Threading.SendOrPostCallback onGetSubscriptionCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetBusDelegate;
        
        private EndOperationDelegate onEndGetBusDelegate;
        
        private System.Threading.SendOrPostCallback onGetBusCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public InformationWebServiceClient() {
        }
        
        public InformationWebServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public InformationWebServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public InformationWebServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public InformationWebServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                            "ookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<GetGeneralInformationCompletedEventArgs> GetGeneralInformationCompleted;
        
        public event System.EventHandler<GetTicketCompletedEventArgs> GetTicketCompleted;
        
        public event System.EventHandler<GetSubscriptionCompletedEventArgs> GetSubscriptionCompleted;
        
        public event System.EventHandler<GetBusCompletedEventArgs> GetBusCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult ReBus.Mobile.InformationServiceReference.IInformationWebService.BeginGetGeneralInformation(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetGeneralInformation(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ReBus.Mobile.InformationServiceReference.GeneralInformationWebServiceModel ReBus.Mobile.InformationServiceReference.IInformationWebService.EndGetGeneralInformation(System.IAsyncResult result) {
            return base.Channel.EndGetGeneralInformation(result);
        }
        
        private System.IAsyncResult OnBeginGetGeneralInformation(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((ReBus.Mobile.InformationServiceReference.IInformationWebService)(this)).BeginGetGeneralInformation(callback, asyncState);
        }
        
        private object[] OnEndGetGeneralInformation(System.IAsyncResult result) {
            ReBus.Mobile.InformationServiceReference.GeneralInformationWebServiceModel retVal = ((ReBus.Mobile.InformationServiceReference.IInformationWebService)(this)).EndGetGeneralInformation(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetGeneralInformationCompleted(object state) {
            if ((this.GetGeneralInformationCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetGeneralInformationCompleted(this, new GetGeneralInformationCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetGeneralInformationAsync() {
            this.GetGeneralInformationAsync(null);
        }
        
        public void GetGeneralInformationAsync(object userState) {
            if ((this.onBeginGetGeneralInformationDelegate == null)) {
                this.onBeginGetGeneralInformationDelegate = new BeginOperationDelegate(this.OnBeginGetGeneralInformation);
            }
            if ((this.onEndGetGeneralInformationDelegate == null)) {
                this.onEndGetGeneralInformationDelegate = new EndOperationDelegate(this.OnEndGetGeneralInformation);
            }
            if ((this.onGetGeneralInformationCompletedDelegate == null)) {
                this.onGetGeneralInformationCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetGeneralInformationCompleted);
            }
            base.InvokeAsync(this.onBeginGetGeneralInformationDelegate, null, this.onEndGetGeneralInformationDelegate, this.onGetGeneralInformationCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult ReBus.Mobile.InformationServiceReference.IInformationWebService.BeginGetTicket(System.Guid guid, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetTicket(guid, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ReBus.Mobile.InformationServiceReference.TicketWebServiceModel ReBus.Mobile.InformationServiceReference.IInformationWebService.EndGetTicket(System.IAsyncResult result) {
            return base.Channel.EndGetTicket(result);
        }
        
        private System.IAsyncResult OnBeginGetTicket(object[] inValues, System.AsyncCallback callback, object asyncState) {
            System.Guid guid = ((System.Guid)(inValues[0]));
            return ((ReBus.Mobile.InformationServiceReference.IInformationWebService)(this)).BeginGetTicket(guid, callback, asyncState);
        }
        
        private object[] OnEndGetTicket(System.IAsyncResult result) {
            ReBus.Mobile.InformationServiceReference.TicketWebServiceModel retVal = ((ReBus.Mobile.InformationServiceReference.IInformationWebService)(this)).EndGetTicket(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetTicketCompleted(object state) {
            if ((this.GetTicketCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetTicketCompleted(this, new GetTicketCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetTicketAsync(System.Guid guid) {
            this.GetTicketAsync(guid, null);
        }
        
        public void GetTicketAsync(System.Guid guid, object userState) {
            if ((this.onBeginGetTicketDelegate == null)) {
                this.onBeginGetTicketDelegate = new BeginOperationDelegate(this.OnBeginGetTicket);
            }
            if ((this.onEndGetTicketDelegate == null)) {
                this.onEndGetTicketDelegate = new EndOperationDelegate(this.OnEndGetTicket);
            }
            if ((this.onGetTicketCompletedDelegate == null)) {
                this.onGetTicketCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetTicketCompleted);
            }
            base.InvokeAsync(this.onBeginGetTicketDelegate, new object[] {
                        guid}, this.onEndGetTicketDelegate, this.onGetTicketCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult ReBus.Mobile.InformationServiceReference.IInformationWebService.BeginGetSubscription(System.Guid guid, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetSubscription(guid, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ReBus.Mobile.InformationServiceReference.SubscriptionWebServiceModel ReBus.Mobile.InformationServiceReference.IInformationWebService.EndGetSubscription(System.IAsyncResult result) {
            return base.Channel.EndGetSubscription(result);
        }
        
        private System.IAsyncResult OnBeginGetSubscription(object[] inValues, System.AsyncCallback callback, object asyncState) {
            System.Guid guid = ((System.Guid)(inValues[0]));
            return ((ReBus.Mobile.InformationServiceReference.IInformationWebService)(this)).BeginGetSubscription(guid, callback, asyncState);
        }
        
        private object[] OnEndGetSubscription(System.IAsyncResult result) {
            ReBus.Mobile.InformationServiceReference.SubscriptionWebServiceModel retVal = ((ReBus.Mobile.InformationServiceReference.IInformationWebService)(this)).EndGetSubscription(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetSubscriptionCompleted(object state) {
            if ((this.GetSubscriptionCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetSubscriptionCompleted(this, new GetSubscriptionCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetSubscriptionAsync(System.Guid guid) {
            this.GetSubscriptionAsync(guid, null);
        }
        
        public void GetSubscriptionAsync(System.Guid guid, object userState) {
            if ((this.onBeginGetSubscriptionDelegate == null)) {
                this.onBeginGetSubscriptionDelegate = new BeginOperationDelegate(this.OnBeginGetSubscription);
            }
            if ((this.onEndGetSubscriptionDelegate == null)) {
                this.onEndGetSubscriptionDelegate = new EndOperationDelegate(this.OnEndGetSubscription);
            }
            if ((this.onGetSubscriptionCompletedDelegate == null)) {
                this.onGetSubscriptionCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetSubscriptionCompleted);
            }
            base.InvokeAsync(this.onBeginGetSubscriptionDelegate, new object[] {
                        guid}, this.onEndGetSubscriptionDelegate, this.onGetSubscriptionCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult ReBus.Mobile.InformationServiceReference.IInformationWebService.BeginGetBus(System.Guid guid, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetBus(guid, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ReBus.Mobile.InformationServiceReference.BusWebServiceModel ReBus.Mobile.InformationServiceReference.IInformationWebService.EndGetBus(System.IAsyncResult result) {
            return base.Channel.EndGetBus(result);
        }
        
        private System.IAsyncResult OnBeginGetBus(object[] inValues, System.AsyncCallback callback, object asyncState) {
            System.Guid guid = ((System.Guid)(inValues[0]));
            return ((ReBus.Mobile.InformationServiceReference.IInformationWebService)(this)).BeginGetBus(guid, callback, asyncState);
        }
        
        private object[] OnEndGetBus(System.IAsyncResult result) {
            ReBus.Mobile.InformationServiceReference.BusWebServiceModel retVal = ((ReBus.Mobile.InformationServiceReference.IInformationWebService)(this)).EndGetBus(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetBusCompleted(object state) {
            if ((this.GetBusCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetBusCompleted(this, new GetBusCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetBusAsync(System.Guid guid) {
            this.GetBusAsync(guid, null);
        }
        
        public void GetBusAsync(System.Guid guid, object userState) {
            if ((this.onBeginGetBusDelegate == null)) {
                this.onBeginGetBusDelegate = new BeginOperationDelegate(this.OnBeginGetBus);
            }
            if ((this.onEndGetBusDelegate == null)) {
                this.onEndGetBusDelegate = new EndOperationDelegate(this.OnEndGetBus);
            }
            if ((this.onGetBusCompletedDelegate == null)) {
                this.onGetBusCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetBusCompleted);
            }
            base.InvokeAsync(this.onBeginGetBusDelegate, new object[] {
                        guid}, this.onEndGetBusDelegate, this.onGetBusCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override ReBus.Mobile.InformationServiceReference.IInformationWebService CreateChannel() {
            return new InformationWebServiceClientChannel(this);
        }
        
        private class InformationWebServiceClientChannel : ChannelBase<ReBus.Mobile.InformationServiceReference.IInformationWebService>, ReBus.Mobile.InformationServiceReference.IInformationWebService {
            
            public InformationWebServiceClientChannel(System.ServiceModel.ClientBase<ReBus.Mobile.InformationServiceReference.IInformationWebService> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginGetGeneralInformation(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("GetGeneralInformation", _args, callback, asyncState);
                return _result;
            }
            
            public ReBus.Mobile.InformationServiceReference.GeneralInformationWebServiceModel EndGetGeneralInformation(System.IAsyncResult result) {
                object[] _args = new object[0];
                ReBus.Mobile.InformationServiceReference.GeneralInformationWebServiceModel _result = ((ReBus.Mobile.InformationServiceReference.GeneralInformationWebServiceModel)(base.EndInvoke("GetGeneralInformation", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetTicket(System.Guid guid, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = guid;
                System.IAsyncResult _result = base.BeginInvoke("GetTicket", _args, callback, asyncState);
                return _result;
            }
            
            public ReBus.Mobile.InformationServiceReference.TicketWebServiceModel EndGetTicket(System.IAsyncResult result) {
                object[] _args = new object[0];
                ReBus.Mobile.InformationServiceReference.TicketWebServiceModel _result = ((ReBus.Mobile.InformationServiceReference.TicketWebServiceModel)(base.EndInvoke("GetTicket", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetSubscription(System.Guid guid, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = guid;
                System.IAsyncResult _result = base.BeginInvoke("GetSubscription", _args, callback, asyncState);
                return _result;
            }
            
            public ReBus.Mobile.InformationServiceReference.SubscriptionWebServiceModel EndGetSubscription(System.IAsyncResult result) {
                object[] _args = new object[0];
                ReBus.Mobile.InformationServiceReference.SubscriptionWebServiceModel _result = ((ReBus.Mobile.InformationServiceReference.SubscriptionWebServiceModel)(base.EndInvoke("GetSubscription", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetBus(System.Guid guid, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = guid;
                System.IAsyncResult _result = base.BeginInvoke("GetBus", _args, callback, asyncState);
                return _result;
            }
            
            public ReBus.Mobile.InformationServiceReference.BusWebServiceModel EndGetBus(System.IAsyncResult result) {
                object[] _args = new object[0];
                ReBus.Mobile.InformationServiceReference.BusWebServiceModel _result = ((ReBus.Mobile.InformationServiceReference.BusWebServiceModel)(base.EndInvoke("GetBus", _args, result)));
                return _result;
            }
        }
    }
}
